env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  react/prop-types: 0,
  no-console: 0,
  import/extensions: 0,
  import/prefer-default-export: 0,
  react/jsx-filename-extension: 0,
  no-param-reassign: 0,
  linebreak-style: 0,
  react/jsx-no-constructed-context-values: 0,
  operator-linebreak: 0,
}